# Generated by Django 5.0.2 on 2024-02-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fometask2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='date_add',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
